### ISSUE TITLE
wrong argument order for http.post in readme synopsis

### ISSUE THREAD

**Issue by torbiak** [loco2/lolsoap#12]
The following line in the readme synopsis needs to have the order of the last two arguments flipped to be consistent with the [stdlib docs](http://www.ruby-doc.org/stdlib-2.2.0/libdoc/net/http/rdoc/Net/HTTP.html#method-i-post).

```
raw_response = http.post(request.url, request.headers, request.content)
```

Also, thanks for the library! I'm really appreciating its flexibility.

**Comment by eugenebolshakov** [comment]
The code in the README is not using `Net::HTTP`:

```
# You will need your own HTTP client
http = MyHttpClient.new
```
