### ISSUE TITLE
Add hash collection to request.body

### ISSUE THREAD

**Issue by joaquinvaldez** [loco2/lolsoap#13]
Hello!

Is it possible if I have a hash of request attributes to add these to request.body ?  Sample code would be appreciated.  

Thanks,
Joaquin

**Comment by eugenebolshakov** [comment]
Hi Joaquin,

lolsoap doesn't allow to specify request attributes as a hash out of the box. If you need that functionality you'll have to write some code that would create a request object as per the readme, and recursively go through the hash and use the keys as method names to be called on the request object.

Hope that helps.

**Comment by joaquinvaldez** [comment]
Thank you!
