### ISSUE TITLE
Error parsing wsdl file

### ISSUE THREAD

**Issue by fernandes** [loco2/lolsoap#16]
Hi,

Sorry about opening this issue, but I started digging into the code and didn't realize what's happening. reading the wsdl can be found online [here](https://api.softlayer.com/soap/v3/SoftLayer_Virtual_Guest?wsdl) I got the following error:

```ruby
NoMethodError: undefined method `include?' for nil:NilClass
from /Users/fernandes/src/softlayer/vendor/bundle/ruby/2.2.0/gems/lolsoap-0.8.0/lib/lolsoap/wsdl_parser.rb:369:in `namespace_and_name'
```

the node I run into problem is this one:

```ruby
=> #(Element:0x3fc86d0ab494 {
  name = "part",
  namespace = #(Namespace:0x3fc86ec0ee20 { href = "http://schemas.xmlsoap.org/wsdl/" }),
  attributes = [
    #(Attr:0x3fc86d0ab46c { name = "name", value = "SoftLayer_Virtual_GuestInitParameters" }),
    #(Attr:0x3fc86ec0f5c8 { name = "type", value = "tns:SoftLayer_Virtual_GuestInitParameters" })]
  })
```

thank you

**Comment by eugenebolshakov** [comment]
Hi @fernandes 

The reason you're getting that error is that lolsoap currently expects message parts in a WSDL to have an `element` attribute, e.g. (from fixtures):

```
<message name="GetLastTradePriceInputHeader">
  <part name="header" element="xsd1:tradePriceRequestHeader"/>
</message>
```

and in your wsdl messages look like this:

```
<message name="SoftLayer_Virtual_GuestInitParametersHeader">
  <part name="SoftLayer_Virtual_GuestInitParameters" type="tns:SoftLayer_Virtual_GuestInitParameters"/>
</message>
```

Essentially, lolsoap doesn't support the entire WSDL spec, but we've made it support just enough to make it usable for our projects at @loco2. This means that unfortunately we won't be able to work on adding support for your WSDL, but we'd obviously welcome a PR if you decide to add that support.

I'm sorry I'm not able to help with this error.

**Comment by fernandes** [comment]
hi @eugenebolshakov 
thank you for your quick reply

as I've seen the format you support is Document/literal, and the problem I'm facing is that my wsdl is rpc/encoded, not sure yet because I'm new to SOAP stuff, but I'm trying to solve on my side... I'm closing as this is not a bug, just not supported... thank you
