### ISSUE TITLE
namespace of attributes not preserved in headers

### ISSUE THREAD

**Issue by akostadinov** [loco2/lolsoap#18]
```
[97] pry(#<CucuShift::DefaultWorld>)> Kernel.puts n.to_xml
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header>
    <ns1:sessionID xmlns:ns1="http://ws.polarion.com/session" soapenv:actor="http://schemas.xmlsoap.org/soap/actor/next" soapenv:mustUnderstand="0">-2947384893281700987</ns1:sessionID>
  </soapenv:Header>
  <soapenv:Body>
    <logInResponse xmlns="http://ws.polarion.com/SessionWebService-impl"/>
  </soapenv:Body>
</soapenv:Envelope>
[99] pry(#<CucuShift::DefaultWorld>)> auth_xml = n.xpath("//*[local-name()='sessionID']")
```

Then I do:
```
get_user.header.__node__ << auth_xml
```

In the response I end up with:
```
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:ns0="http://ws.polarion.com/types" xmlns:ns1="http://ws.polarion.com/ProjectWebService-types" xmlns:ns2="http://ws.polarion.com/ProjectWebService-impl" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header>
    <ns1:sessionID xmlns:ns1="http://ws.polarion.com/session" actor="http://schemas.xmlsoap.org/soap/actor/next" mustUnderstand="0">-2947384893281700987</ns1:sessionID>
  </soap:Header>
  <soap:Body>
    <ns2:getUser>
      <ns2:userID>akostadi</ns2:userID>
    </ns2:getUser>
  </soap:Body>
</soap:Envelope>
```

Basically the `actor` and `mustUnderstand` attributes have been washed off their namespaces. Any idea how to fix this?

**Comment by akostadinov** [comment]
I think it is actually this bug sparklemotion/nokogiri#1200

Basically adding non-cloned element to another element may well result in bad namespace handling. I think that this needs to be fixed in the underlying libraries as making losoap too smart would be a double edged sword.

But still it's worth putting this somewhere in lolsoap documentation to avoid user confusion. Using WSDL is a heavily namespaced business if I can say it like that. Adding headers is a common operation and a warning in the readme will be well worth it IMO.

**Comment by eugenebolshakov** [comment]
This example in the README https://github.com/loco2/lolsoap#wsse is for WSSE using `akami` gem only. The gem takes care of the namespaces. 

If you need to build a customer header you can just do so in the same way you'd build a body (clarified this in the README in b5f22ea798e7a03b85f57839d464b23898bf5d6c):

```
request.header do |header|
  header.sessionID "-2947384893281700987"
  header.sessionID do |sid|
    sid.action "..."
  end
end
```

I'm closing this as it's not a lolsoap bug.
