### ISSUE TITLE
HashBuilder does not support element attributes

### ISSUE THREAD

**Issue by akostadinov** [loco2/lolsoap#23]
Hello, I don't see element attributes being returned in the `#body_hash` call. It would be very useful to output attributes as well as subelements.

I'm not sure how a sigular element with attributes can be handled though. Not that I need it but how can this be approached?

**Comment by eugenebolshakov** [comment]
The reason `LolSoap#HashBuilder` ignores attributes is that we basically don't need that functionality. We use `LolSoap#HashBuilder` for simple API responses and in more complex cases (and that's where we care about attributes) we just use xpath to parse the response. We'd welcome a PR, but I'm not sure what the best way to include attributes in a resulting hash would be (and also don't have a good answer to your question about a single element with attributes). 

I'll close this bug, but happy to look into a PR if you want to come up with one.
