### ISSUE TITLE
undefined method `has_attribute?` when calling `request.header`

### ISSUE THREAD

**Issue by PhilT** [loco2/lolsoap#25]
I'm trying to set a Cookie header

```
request.header do |h|
  h.Cookie "ss-id=#{session_id}"
end
```

But I get:

```
NoMethodError: undefined method `has_attribute?' for #<LolSoap::WSDL::NullType:0x007fffc3c70b30>
from /home/phil/.gem/ruby/2.3.4/gems/lolsoap-0.8.3/lib/lolsoap/builder.rb:107:in `method_missing'
```

Any ideas?

**Comment by eugenebolshakov** [comment]
`request.header` is used for building a SOAP Header XML Element, e.g.: https://github.com/loco2/lolsoap/blob/master/test/integration/test_envelope.rb#L39-L49 and not for setting HTTP headers. 

The way to set a cookie depends on the http client that you're using. You'll likely need to set any HTTP headers when you a make a HTTP request and merge them with the headers that LolSoap generates. E.g. from the Readme:

```
# You will need your own HTTP client
http = MyHttpClient.new

[...]

# Send that request!
raw_response = http.post(request.url, request.headers.merge(your_http_headers), request.content)
```

Hope that makes sense!

**Comment by PhilT** [comment]
Doh! Of course. Thanks very much.
